### ISSUE TITLE
windows install problems

### ISSUE THREAD

**Issue by AEljarrat** [hyperspy/hyperspy-doc#3]
Dear all, 

there is an issue in the windows installation of hyperspy that one encounters because some packages (traits, traitsui...) have to be compiled with C++. When the C++ compiler variable is not correctly defined, the command "pip install hyperspy" will fail with message "error: Unable to find vcvarsall.bat". The C++ compiler variables are specific of your python installation, e.g. I was using python 3.4 which is compiled with VS140COMNTOOLS. This means it does not suffice with having a C++ compiler installed, the environment variable has to be there. Also, the Visual Studio redistributables where no good (for me) I had to install the full Visual Studio Community. 

Other solution (given by Josh Taillon) is to use a precompiled C package that matches your Python distribution.

For the average user of Hyperspy, it seems both solutions are medium/advanced, so there should be somehow a recomendation in the docs?

Sincerely,
Alberto.

**Comment by ericpre** [comment]
This has been working fine since a few years with conda-forge packaging and wheels provided on pypi!
